server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback: todas las rutas que no son archivos van al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Gzip para performance
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/javascript;
    gzip_min_length 1024;
}
