sonar.projectKey=plataforma-colegio-ohiggins-oficial
sonar.organization=yaquelin2305
sonar.sources=src
sonar.exclusions=src/test/**,src/main.jsx
sonar.tests=src/test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
