server:
  port: 8084

spring:
  application:
    name: ms-bff

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info

---
spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    openfeign:
      client:
        config:
          ms-usuario:
            url: ${USUARIO_URL:http://ms-usuario:8083}
          ms-academico:
            url: ${ACADEMICO_URL:http://ms-academico:8082}
          ms-comunicaciones:
            url: ${COMUNICACIONES_URL:http://ms-comunicaciones:8085}
          ms-asistencia:
            url: ${ASISTENCIA_URL:http://ms-asistencia:8085}

eureka:
  client:
    enabled: false
