server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notificaciones_db
    username: postgres
    password: ${DB_PASSWORD}  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    enabled: false